name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
   
  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          CYPRESS_MAILOSAUR_SERVER_ID: ${{ secrets.CYPRESS_MAILOSAUR_SERVER_ID }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
        with:
          record: false
          command: npm test
      
      - name: Gravar vídeo
        uses: cypress-io/github-action@v5
        with:
          record: false
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos

          
